# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contacts.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_contactsDialog(object):
    def setupUi(self, contactsDialog):
        contactsDialog.setObjectName(_fromUtf8("contactsDialog"))
        contactsDialog.resize(633, 631)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/edit-user.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        contactsDialog.setWindowIcon(icon)
        contactsDialog.setWindowOpacity(1.0)
        contactsDialog.setStyleSheet(_fromUtf8(""))
        self.nameFrame = QtGui.QFrame(contactsDialog)
        self.nameFrame.setGeometry(QtCore.QRect(10, 10, 611, 141))
        self.nameFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.nameFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.nameFrame.setObjectName(_fromUtf8("nameFrame"))
        self.layoutWidget = QtGui.QWidget(self.nameFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 91, 591, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.credLabel = QtGui.QLabel(self.layoutWidget)
        self.credLabel.setObjectName(_fromUtf8("credLabel"))
        self.horizontalLayout_3.addWidget(self.credLabel)
        self.credLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.credLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(211, 213, 244);"))
        self.credLineEdit.setObjectName(_fromUtf8("credLineEdit"))
        self.horizontalLayout_3.addWidget(self.credLineEdit)
        self.layoutWidget1 = QtGui.QWidget(self.nameFrame)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 591, 41))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.mrmrsLabel = QtGui.QLabel(self.layoutWidget1)
        self.mrmrsLabel.setMaximumSize(QtCore.QSize(55, 16777215))
        self.mrmrsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mrmrsLabel.setObjectName(_fromUtf8("mrmrsLabel"))
        self.horizontalLayout_2.addWidget(self.mrmrsLabel)
        self.mrmrsLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.mrmrsLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.mrmrsLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(211, 213, 244);"))
        self.mrmrsLineEdit.setObjectName(_fromUtf8("mrmrsLineEdit"))
        self.horizontalLayout_2.addWidget(self.mrmrsLineEdit)
        self.firstnameLabel = QtGui.QLabel(self.layoutWidget1)
        self.firstnameLabel.setMaximumSize(QtCore.QSize(40, 16777215))
        self.firstnameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.firstnameLabel.setObjectName(_fromUtf8("firstnameLabel"))
        self.horizontalLayout_2.addWidget(self.firstnameLabel)
        self.firstNameLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.firstNameLineEdit.setMaximumSize(QtCore.QSize(160, 16777215))
        self.firstNameLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(211, 213, 244);"))
        self.firstNameLineEdit.setObjectName(_fromUtf8("firstNameLineEdit"))
        self.horizontalLayout_2.addWidget(self.firstNameLineEdit)
        self.middleNameLabel = QtGui.QLabel(self.layoutWidget1)
        self.middleNameLabel.setMaximumSize(QtCore.QSize(30, 16777215))
        self.middleNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.middleNameLabel.setObjectName(_fromUtf8("middleNameLabel"))
        self.horizontalLayout_2.addWidget(self.middleNameLabel)
        self.middleNameLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middleNameLineEdit.sizePolicy().hasHeightForWidth())
        self.middleNameLineEdit.setSizePolicy(sizePolicy)
        self.middleNameLineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.middleNameLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(211, 213, 244);"))
        self.middleNameLineEdit.setObjectName(_fromUtf8("middleNameLineEdit"))
        self.horizontalLayout_2.addWidget(self.middleNameLineEdit)
        self.lastNameLabel = QtGui.QLabel(self.layoutWidget1)
        self.lastNameLabel.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lastNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lastNameLabel.setObjectName(_fromUtf8("lastNameLabel"))
        self.horizontalLayout_2.addWidget(self.lastNameLabel)
        self.lastNameLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.lastNameLineEdit.setMaximumSize(QtCore.QSize(160, 16777215))
        self.lastNameLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(211, 213, 244);"))
        self.lastNameLineEdit.setObjectName(_fromUtf8("lastNameLineEdit"))
        self.horizontalLayout_2.addWidget(self.lastNameLineEdit)
        self.layoutWidget2 = QtGui.QWidget(self.nameFrame)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 591, 41))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.companyLabel = QtGui.QLabel(self.layoutWidget2)
        self.companyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.companyLabel.setObjectName(_fromUtf8("companyLabel"))
        self.horizontalLayout.addWidget(self.companyLabel)
        self.companyLineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.companyLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.companyLineEdit.setObjectName(_fromUtf8("companyLineEdit"))
        self.horizontalLayout.addWidget(self.companyLineEdit)
        self.contactTabWidget = QtGui.QTabWidget(contactsDialog)
        self.contactTabWidget.setGeometry(QtCore.QRect(10, 170, 611, 411))
        self.contactTabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.contactTabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.contactTabWidget.setTabsClosable(False)
        self.contactTabWidget.setMovable(True)
        self.contactTabWidget.setObjectName(_fromUtf8("contactTabWidget"))
        self.contactTab = QtGui.QWidget()
        self.contactTab.setObjectName(_fromUtf8("contactTab"))
        self.line_2 = QtGui.QFrame(self.contactTab)
        self.line_2.setGeometry(QtCore.QRect(310, 20, 20, 151))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.contactTab)
        self.line_3.setGeometry(QtCore.QRect(20, 170, 571, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.layoutWidget3 = QtGui.QWidget(self.contactTab)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 190, 591, 179))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.officeEmailLabel = QtGui.QLabel(self.layoutWidget3)
        self.officeEmailLabel.setObjectName(_fromUtf8("officeEmailLabel"))
        self.gridLayout_3.addWidget(self.officeEmailLabel, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.officeEmailLineEdit = QtGui.QLineEdit(self.layoutWidget3)
        self.officeEmailLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.officeEmailLineEdit.setObjectName(_fromUtf8("officeEmailLineEdit"))
        self.gridLayout_3.addWidget(self.officeEmailLineEdit, 0, 1, 1, 1)
        self.personalEmailLabel = QtGui.QLabel(self.layoutWidget3)
        self.personalEmailLabel.setObjectName(_fromUtf8("personalEmailLabel"))
        self.gridLayout_3.addWidget(self.personalEmailLabel, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.personalEmailLineEdit = QtGui.QLineEdit(self.layoutWidget3)
        self.personalEmailLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.personalEmailLineEdit.setObjectName(_fromUtf8("personalEmailLineEdit"))
        self.gridLayout_3.addWidget(self.personalEmailLineEdit, 1, 1, 1, 1)
        self.officeWebLabel = QtGui.QLabel(self.layoutWidget3)
        self.officeWebLabel.setObjectName(_fromUtf8("officeWebLabel"))
        self.gridLayout_3.addWidget(self.officeWebLabel, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.officeWebLineEdit = QtGui.QLineEdit(self.layoutWidget3)
        self.officeWebLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.officeWebLineEdit.setObjectName(_fromUtf8("officeWebLineEdit"))
        self.gridLayout_3.addWidget(self.officeWebLineEdit, 2, 1, 1, 1)
        self.personalWebLabel = QtGui.QLabel(self.layoutWidget3)
        self.personalWebLabel.setObjectName(_fromUtf8("personalWebLabel"))
        self.gridLayout_3.addWidget(self.personalWebLabel, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.personalWebLineEdit = QtGui.QLineEdit(self.layoutWidget3)
        self.personalWebLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.personalWebLineEdit.setObjectName(_fromUtf8("personalWebLineEdit"))
        self.gridLayout_3.addWidget(self.personalWebLineEdit, 3, 1, 1, 1)
        self.picFrame = QtGui.QFrame(self.contactTab)
        self.picFrame.setGeometry(QtCore.QRect(370, 20, 161, 151))
        self.picFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.picFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.picFrame.setObjectName(_fromUtf8("picFrame"))
        self.picLabel = QtGui.QLabel(self.picFrame)
        self.picLabel.setGeometry(QtCore.QRect(10, 10, 141, 131))
        self.picLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.picLabel.setText(_fromUtf8(""))
        self.picLabel.setPixmap(QtGui.QPixmap(_fromUtf8("default.jpg")))
        self.picLabel.setScaledContents(True)
        self.picLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.picLabel.setObjectName(_fromUtf8("picLabel"))
        self.layoutWidget4 = QtGui.QWidget(self.contactTab)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 301, 151))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cellPhoneLabel = QtGui.QLabel(self.layoutWidget4)
        self.cellPhoneLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cellPhoneLabel.setObjectName(_fromUtf8("cellPhoneLabel"))
        self.gridLayout_2.addWidget(self.cellPhoneLabel, 0, 0, 1, 1)
        self.cellPhoneLineEdit = QtGui.QLineEdit(self.layoutWidget4)
        self.cellPhoneLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.cellPhoneLineEdit.setObjectName(_fromUtf8("cellPhoneLineEdit"))
        self.gridLayout_2.addWidget(self.cellPhoneLineEdit, 0, 1, 1, 1)
        self.homePhoneLabel = QtGui.QLabel(self.layoutWidget4)
        self.homePhoneLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.homePhoneLabel.setObjectName(_fromUtf8("homePhoneLabel"))
        self.gridLayout_2.addWidget(self.homePhoneLabel, 1, 0, 1, 1)
        self.homePhoneLineEdit = QtGui.QLineEdit(self.layoutWidget4)
        self.homePhoneLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.homePhoneLineEdit.setObjectName(_fromUtf8("homePhoneLineEdit"))
        self.gridLayout_2.addWidget(self.homePhoneLineEdit, 1, 1, 1, 1)
        self.officePhoneLabel = QtGui.QLabel(self.layoutWidget4)
        self.officePhoneLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.officePhoneLabel.setObjectName(_fromUtf8("officePhoneLabel"))
        self.gridLayout_2.addWidget(self.officePhoneLabel, 2, 0, 1, 1)
        self.officePhoneLineEdit = QtGui.QLineEdit(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.officePhoneLineEdit.sizePolicy().hasHeightForWidth())
        self.officePhoneLineEdit.setSizePolicy(sizePolicy)
        self.officePhoneLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(211, 213, 244);"))
        self.officePhoneLineEdit.setObjectName(_fromUtf8("officePhoneLineEdit"))
        self.gridLayout_2.addWidget(self.officePhoneLineEdit, 2, 1, 1, 1)
        self.officeFaxLabel = QtGui.QLabel(self.layoutWidget4)
        self.officeFaxLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.officeFaxLabel.setObjectName(_fromUtf8("officeFaxLabel"))
        self.gridLayout_2.addWidget(self.officeFaxLabel, 3, 0, 1, 1)
        self.officeFaxLineEdit = QtGui.QLineEdit(self.layoutWidget4)
        self.officeFaxLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.officeFaxLineEdit.setObjectName(_fromUtf8("officeFaxLineEdit"))
        self.gridLayout_2.addWidget(self.officeFaxLineEdit, 3, 1, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/contact-new-2.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactTabWidget.addTab(self.contactTab, icon1, _fromUtf8(""))
        self.addressTab = QtGui.QWidget()
        self.addressTab.setObjectName(_fromUtf8("addressTab"))
        self.frame = QtGui.QFrame(self.addressTab)
        self.frame.setGeometry(QtCore.QRect(10, 10, 581, 271))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.layoutWidget5 = QtGui.QWidget(self.frame)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 30, 541, 221))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.addressLlabel = QtGui.QLabel(self.layoutWidget5)
        self.addressLlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.addressLlabel.setObjectName(_fromUtf8("addressLlabel"))
        self.gridLayout.addWidget(self.addressLlabel, 0, 0, 1, 1)
        self.addressLineEdit = QtGui.QLineEdit(self.layoutWidget5)
        self.addressLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.addressLineEdit.setObjectName(_fromUtf8("addressLineEdit"))
        self.gridLayout.addWidget(self.addressLineEdit, 0, 1, 1, 1)
        self.suiteLabel = QtGui.QLabel(self.layoutWidget5)
        self.suiteLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.suiteLabel.setObjectName(_fromUtf8("suiteLabel"))
        self.gridLayout.addWidget(self.suiteLabel, 1, 0, 1, 1)
        self.suiteLineEdit = QtGui.QLineEdit(self.layoutWidget5)
        self.suiteLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.suiteLineEdit.setObjectName(_fromUtf8("suiteLineEdit"))
        self.gridLayout.addWidget(self.suiteLineEdit, 1, 1, 1, 1)
        self.cityLabel = QtGui.QLabel(self.layoutWidget5)
        self.cityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cityLabel.setObjectName(_fromUtf8("cityLabel"))
        self.gridLayout.addWidget(self.cityLabel, 2, 0, 1, 1)
        self.cityLineEdit = QtGui.QLineEdit(self.layoutWidget5)
        self.cityLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.cityLineEdit.setObjectName(_fromUtf8("cityLineEdit"))
        self.gridLayout.addWidget(self.cityLineEdit, 2, 1, 1, 1)
        self.stateLabel = QtGui.QLabel(self.layoutWidget5)
        self.stateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stateLabel.setObjectName(_fromUtf8("stateLabel"))
        self.gridLayout.addWidget(self.stateLabel, 3, 0, 1, 1)
        self.stateLineEdit = QtGui.QLineEdit(self.layoutWidget5)
        self.stateLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.stateLineEdit.setObjectName(_fromUtf8("stateLineEdit"))
        self.gridLayout.addWidget(self.stateLineEdit, 3, 1, 1, 1)
        self.postalLabel = QtGui.QLabel(self.layoutWidget5)
        self.postalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.postalLabel.setObjectName(_fromUtf8("postalLabel"))
        self.gridLayout.addWidget(self.postalLabel, 4, 0, 1, 1)
        self.postalLineEdit = QtGui.QLineEdit(self.layoutWidget5)
        self.postalLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.postalLineEdit.setObjectName(_fromUtf8("postalLineEdit"))
        self.gridLayout.addWidget(self.postalLineEdit, 4, 1, 1, 1)
        self.layoutWidget6 = QtGui.QWidget(self.addressTab)
        self.layoutWidget6.setGeometry(QtCore.QRect(200, 290, 391, 41))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.copyGroupAddressLabel = QtGui.QLabel(self.layoutWidget6)
        self.copyGroupAddressLabel.setObjectName(_fromUtf8("copyGroupAddressLabel"))
        self.horizontalLayout_4.addWidget(self.copyGroupAddressLabel)
        self.copyGroupAddressLineEdit = QtGui.QLineEdit(self.layoutWidget6)
        self.copyGroupAddressLineEdit.setObjectName(_fromUtf8("copyGroupAddressLineEdit"))
        self.horizontalLayout_4.addWidget(self.copyGroupAddressLineEdit)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/address-book-new-2.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactTabWidget.addTab(self.addressTab, icon2, _fromUtf8(""))
        self.line = QtGui.QFrame(contactsDialog)
        self.line.setGeometry(QtCore.QRect(10, 150, 611, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.savePushButton = QtGui.QPushButton(contactsDialog)
        self.savePushButton.setGeometry(QtCore.QRect(525, 590, 99, 27))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/db_add.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.savePushButton.setIcon(icon3)
        self.savePushButton.setObjectName(_fromUtf8("savePushButton"))
        self.cancelPushButton = QtGui.QPushButton(contactsDialog)
        self.cancelPushButton.setGeometry(QtCore.QRect(420, 590, 99, 27))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/process-stop-5.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.cancelPushButton.setIcon(icon4)
        self.cancelPushButton.setObjectName(_fromUtf8("cancelPushButton"))
        self.label = QtGui.QLabel(contactsDialog)
        self.label.setGeometry(QtCore.QRect(10, 590, 161, 21))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/bristo_logo.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.credLabel.setBuddy(self.credLineEdit)
        self.mrmrsLabel.setBuddy(self.mrmrsLineEdit)
        self.firstnameLabel.setBuddy(self.firstNameLineEdit)
        self.middleNameLabel.setBuddy(self.middleNameLineEdit)
        self.lastNameLabel.setBuddy(self.lastNameLineEdit)
        self.companyLabel.setBuddy(self.companyLineEdit)
        self.officeEmailLabel.setBuddy(self.officeEmailLineEdit)
        self.personalEmailLabel.setBuddy(self.personalEmailLineEdit)
        self.officeWebLabel.setBuddy(self.officeWebLineEdit)
        self.personalWebLabel.setBuddy(self.personalWebLineEdit)
        self.cellPhoneLabel.setBuddy(self.cellPhoneLineEdit)
        self.homePhoneLabel.setBuddy(self.homePhoneLineEdit)
        self.officePhoneLabel.setBuddy(self.officePhoneLineEdit)
        self.officeFaxLabel.setBuddy(self.officeFaxLineEdit)
        self.addressLlabel.setBuddy(self.addressLineEdit)
        self.suiteLabel.setBuddy(self.suiteLineEdit)
        self.cityLabel.setBuddy(self.cityLineEdit)
        self.stateLabel.setBuddy(self.stateLineEdit)
        self.postalLabel.setBuddy(self.postalLineEdit)
        self.copyGroupAddressLabel.setBuddy(self.copyGroupAddressLineEdit)

        self.retranslateUi(contactsDialog)
        self.contactTabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.savePushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), contactsDialog.accept)
        QtCore.QObject.connect(self.cancelPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), contactsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(contactsDialog)
        contactsDialog.setTabOrder(self.companyLineEdit, self.mrmrsLineEdit)
        contactsDialog.setTabOrder(self.mrmrsLineEdit, self.firstNameLineEdit)
        contactsDialog.setTabOrder(self.firstNameLineEdit, self.middleNameLineEdit)
        contactsDialog.setTabOrder(self.middleNameLineEdit, self.lastNameLineEdit)
        contactsDialog.setTabOrder(self.lastNameLineEdit, self.credLineEdit)
        contactsDialog.setTabOrder(self.credLineEdit, self.cellPhoneLineEdit)
        contactsDialog.setTabOrder(self.cellPhoneLineEdit, self.homePhoneLineEdit)
        contactsDialog.setTabOrder(self.homePhoneLineEdit, self.officePhoneLineEdit)
        contactsDialog.setTabOrder(self.officePhoneLineEdit, self.officeFaxLineEdit)
        contactsDialog.setTabOrder(self.officeFaxLineEdit, self.officeEmailLineEdit)
        contactsDialog.setTabOrder(self.officeEmailLineEdit, self.personalEmailLineEdit)
        contactsDialog.setTabOrder(self.personalEmailLineEdit, self.officeWebLineEdit)
        contactsDialog.setTabOrder(self.officeWebLineEdit, self.personalWebLineEdit)
        contactsDialog.setTabOrder(self.personalWebLineEdit, self.addressLineEdit)
        contactsDialog.setTabOrder(self.addressLineEdit, self.suiteLineEdit)
        contactsDialog.setTabOrder(self.suiteLineEdit, self.cityLineEdit)
        contactsDialog.setTabOrder(self.cityLineEdit, self.stateLineEdit)
        contactsDialog.setTabOrder(self.stateLineEdit, self.postalLineEdit)
        contactsDialog.setTabOrder(self.postalLineEdit, self.savePushButton)
        contactsDialog.setTabOrder(self.savePushButton, self.cancelPushButton)
        contactsDialog.setTabOrder(self.cancelPushButton, self.contactTabWidget)

    def retranslateUi(self, contactsDialog):
        contactsDialog.setWindowTitle(_translate("contactsDialog", "Contacts Dialog", None))
        self.credLabel.setText(_translate("contactsDialog", "Title:", None))
        self.mrmrsLabel.setText(_translate("contactsDialog", "Mr/Mrs:", None))
        self.firstnameLabel.setText(_translate("contactsDialog", "First :", None))
        self.middleNameLabel.setText(_translate("contactsDialog", "M:", None))
        self.lastNameLabel.setText(_translate("contactsDialog", "Last:", None))
        self.companyLabel.setText(_translate("contactsDialog", "Company/Organization:", None))
        self.officeEmailLabel.setText(_translate("contactsDialog", "Office Email:", None))
        self.personalEmailLabel.setText(_translate("contactsDialog", "Personal Email:", None))
        self.officeWebLabel.setText(_translate("contactsDialog", "Office Web:", None))
        self.personalWebLabel.setText(_translate("contactsDialog", "Personal Web:", None))
        self.cellPhoneLabel.setText(_translate("contactsDialog", "Cell Phone:", None))
        self.homePhoneLabel.setText(_translate("contactsDialog", "Home Phone:", None))
        self.officePhoneLabel.setText(_translate("contactsDialog", "Office Phone:", None))
        self.officeFaxLabel.setText(_translate("contactsDialog", "Office Fax:", None))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.contactTab), _translate("contactsDialog", "Contact", None))
        self.addressLlabel.setText(_translate("contactsDialog", "Address:", None))
        self.suiteLabel.setText(_translate("contactsDialog", "Suite/ Floor:", None))
        self.cityLabel.setText(_translate("contactsDialog", "City:", None))
        self.stateLabel.setText(_translate("contactsDialog", "State/Province:", None))
        self.postalLabel.setText(_translate("contactsDialog", "Zip:", None))
        self.copyGroupAddressLabel.setText(_translate("contactsDialog", "Enter Group Name to copy:", None))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.addressTab), _translate("contactsDialog", "Office Address", None))
        self.savePushButton.setText(_translate("contactsDialog", "Save", None))
        self.cancelPushButton.setText(_translate("contactsDialog", "Cancel", None))

import resources_rc
