#!/usr/bin/python2
#
# Copyright 2016 Kirk A Jackson DBA bristoSOFT all rights reserved.  All methods,
# techniques, algorithms are confidential trade secrets under Ohio and U.S. 
# Federal law owned by bristoSOFT.
#
'''

main.py is the startup module for bristoSOFT Contacts v. 0.1 in the
Model/View Controller context.  The model is a Postresql database and the view
consist of interfaces generated by Qt Designer.

'''

# Version assignment
__version__ = '0.1'

# Imports
import sys
import controller
from PyQt4.QtCore import *
from PyQt4.QtGui import *

def main():
    app = QApplication(sys.argv)
    contacts = controller.Controller()
    contacts.setWindowIcon(QIcon(":icons/family.ico"))
    contacts.show()
    app.exec_()

if __name__ == '__main__':
    main()
