# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_contactsSearchDialog(object):
    def setupUi(self, contactsSearchDialog):
        contactsSearchDialog.setObjectName(_fromUtf8("contactsSearchDialog"))
        contactsSearchDialog.resize(632, 655)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(contactsSearchDialog.sizePolicy().hasHeightForWidth())
        contactsSearchDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/edit-user.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        contactsSearchDialog.setWindowIcon(icon)
        contactsSearchDialog.setWindowOpacity(1.0)
        contactsSearchDialog.setStyleSheet(_fromUtf8(""))
        contactsSearchDialog.setSizeGripEnabled(False)
        self.nameFrame = QtGui.QFrame(contactsSearchDialog)
        self.nameFrame.setGeometry(QtCore.QRect(10, 10, 611, 141))
        self.nameFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.nameFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.nameFrame.setObjectName(_fromUtf8("nameFrame"))
        self.layoutWidget = QtGui.QWidget(self.nameFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 91, 591, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.credLabel = QtGui.QLabel(self.layoutWidget)
        self.credLabel.setObjectName(_fromUtf8("credLabel"))
        self.horizontalLayout_3.addWidget(self.credLabel)
        self.credLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.credLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(211, 213, 244);"))
        self.credLineEdit.setObjectName(_fromUtf8("credLineEdit"))
        self.horizontalLayout_3.addWidget(self.credLineEdit)
        self.layoutWidget1 = QtGui.QWidget(self.nameFrame)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 51, 591, 41))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.mrmrsLabel = QtGui.QLabel(self.layoutWidget1)
        self.mrmrsLabel.setMaximumSize(QtCore.QSize(55, 16777215))
        self.mrmrsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mrmrsLabel.setObjectName(_fromUtf8("mrmrsLabel"))
        self.horizontalLayout_2.addWidget(self.mrmrsLabel)
        self.mrmrsLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.mrmrsLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.mrmrsLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(211, 213, 244);"))
        self.mrmrsLineEdit.setObjectName(_fromUtf8("mrmrsLineEdit"))
        self.horizontalLayout_2.addWidget(self.mrmrsLineEdit)
        self.firstnameLabel = QtGui.QLabel(self.layoutWidget1)
        self.firstnameLabel.setMaximumSize(QtCore.QSize(40, 16777215))
        self.firstnameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.firstnameLabel.setObjectName(_fromUtf8("firstnameLabel"))
        self.horizontalLayout_2.addWidget(self.firstnameLabel)
        self.firstNameLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.firstNameLineEdit.setMaximumSize(QtCore.QSize(160, 16777215))
        self.firstNameLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(211, 213, 244);"))
        self.firstNameLineEdit.setObjectName(_fromUtf8("firstNameLineEdit"))
        self.horizontalLayout_2.addWidget(self.firstNameLineEdit)
        self.middleNameLabel = QtGui.QLabel(self.layoutWidget1)
        self.middleNameLabel.setMaximumSize(QtCore.QSize(30, 16777215))
        self.middleNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.middleNameLabel.setObjectName(_fromUtf8("middleNameLabel"))
        self.horizontalLayout_2.addWidget(self.middleNameLabel)
        self.middleNameLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middleNameLineEdit.sizePolicy().hasHeightForWidth())
        self.middleNameLineEdit.setSizePolicy(sizePolicy)
        self.middleNameLineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.middleNameLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(211, 213, 244);"))
        self.middleNameLineEdit.setObjectName(_fromUtf8("middleNameLineEdit"))
        self.horizontalLayout_2.addWidget(self.middleNameLineEdit)
        self.lastNameLabel = QtGui.QLabel(self.layoutWidget1)
        self.lastNameLabel.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lastNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lastNameLabel.setObjectName(_fromUtf8("lastNameLabel"))
        self.horizontalLayout_2.addWidget(self.lastNameLabel)
        self.lastNameLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.lastNameLineEdit.setMaximumSize(QtCore.QSize(160, 16777215))
        self.lastNameLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(211, 213, 244);"))
        self.lastNameLineEdit.setObjectName(_fromUtf8("lastNameLineEdit"))
        self.horizontalLayout_2.addWidget(self.lastNameLineEdit)
        self.layoutWidget2 = QtGui.QWidget(self.nameFrame)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 11, 591, 41))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.companyLabel = QtGui.QLabel(self.layoutWidget2)
        self.companyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.companyLabel.setObjectName(_fromUtf8("companyLabel"))
        self.horizontalLayout.addWidget(self.companyLabel)
        self.companyLineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.companyLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.companyLineEdit.setObjectName(_fromUtf8("companyLineEdit"))
        self.horizontalLayout.addWidget(self.companyLineEdit)
        self.contactTabWidget = QtGui.QTabWidget(contactsSearchDialog)
        self.contactTabWidget.setGeometry(QtCore.QRect(10, 170, 611, 441))
        self.contactTabWidget.setAcceptDrops(True)
        self.contactTabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.contactTabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.contactTabWidget.setDocumentMode(False)
        self.contactTabWidget.setTabsClosable(False)
        self.contactTabWidget.setMovable(True)
        self.contactTabWidget.setObjectName(_fromUtf8("contactTabWidget"))
        self.contactTab = QtGui.QWidget()
        self.contactTab.setObjectName(_fromUtf8("contactTab"))
        self.line_2 = QtGui.QFrame(self.contactTab)
        self.line_2.setGeometry(QtCore.QRect(310, 20, 20, 201))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.contactTab)
        self.line_3.setGeometry(QtCore.QRect(0, 220, 591, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.picFrame = QtGui.QFrame(self.contactTab)
        self.picFrame.setGeometry(QtCore.QRect(330, 20, 221, 201))
        self.picFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.picFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.picFrame.setObjectName(_fromUtf8("picFrame"))
        self.picLabel = QtGui.QLabel(self.picFrame)
        self.picLabel.setGeometry(QtCore.QRect(10, 10, 201, 181))
        self.picLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.picLabel.setText(_fromUtf8(""))
        self.picLabel.setPixmap(QtGui.QPixmap(_fromUtf8("default.jpg")))
        self.picLabel.setScaledContents(True)
        self.picLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.picLabel.setObjectName(_fromUtf8("picLabel"))
        self.picPushButton = QtGui.QPushButton(self.contactTab)
        self.picPushButton.setGeometry(QtCore.QRect(560, 190, 31, 31))
        self.picPushButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/document-open-2.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.picPushButton.setIcon(icon1)
        self.picPushButton.setObjectName(_fromUtf8("picPushButton"))
        self.layoutWidget3 = QtGui.QWidget(self.contactTab)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 301, 151))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cellPhoneLabel = QtGui.QLabel(self.layoutWidget3)
        self.cellPhoneLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cellPhoneLabel.setObjectName(_fromUtf8("cellPhoneLabel"))
        self.gridLayout_2.addWidget(self.cellPhoneLabel, 0, 0, 1, 1)
        self.cellPhoneLineEdit = QtGui.QLineEdit(self.layoutWidget3)
        self.cellPhoneLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.cellPhoneLineEdit.setObjectName(_fromUtf8("cellPhoneLineEdit"))
        self.gridLayout_2.addWidget(self.cellPhoneLineEdit, 0, 1, 1, 1)
        self.homePhoneLabel = QtGui.QLabel(self.layoutWidget3)
        self.homePhoneLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.homePhoneLabel.setObjectName(_fromUtf8("homePhoneLabel"))
        self.gridLayout_2.addWidget(self.homePhoneLabel, 1, 0, 1, 1)
        self.homePhoneLineEdit = QtGui.QLineEdit(self.layoutWidget3)
        self.homePhoneLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.homePhoneLineEdit.setObjectName(_fromUtf8("homePhoneLineEdit"))
        self.gridLayout_2.addWidget(self.homePhoneLineEdit, 1, 1, 1, 1)
        self.officePhoneLabel = QtGui.QLabel(self.layoutWidget3)
        self.officePhoneLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.officePhoneLabel.setObjectName(_fromUtf8("officePhoneLabel"))
        self.gridLayout_2.addWidget(self.officePhoneLabel, 2, 0, 1, 1)
        self.officePhoneLineEdit = QtGui.QLineEdit(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.officePhoneLineEdit.sizePolicy().hasHeightForWidth())
        self.officePhoneLineEdit.setSizePolicy(sizePolicy)
        self.officePhoneLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(211, 213, 244);"))
        self.officePhoneLineEdit.setObjectName(_fromUtf8("officePhoneLineEdit"))
        self.gridLayout_2.addWidget(self.officePhoneLineEdit, 2, 1, 1, 1)
        self.officeFaxLabel = QtGui.QLabel(self.layoutWidget3)
        self.officeFaxLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.officeFaxLabel.setObjectName(_fromUtf8("officeFaxLabel"))
        self.gridLayout_2.addWidget(self.officeFaxLabel, 3, 0, 1, 1)
        self.officeFaxLineEdit = QtGui.QLineEdit(self.layoutWidget3)
        self.officeFaxLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.officeFaxLineEdit.setObjectName(_fromUtf8("officeFaxLineEdit"))
        self.gridLayout_2.addWidget(self.officeFaxLineEdit, 3, 1, 1, 1)
        self.layoutWidget4 = QtGui.QWidget(self.contactTab)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 237, 591, 171))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.officeEmailLabel = QtGui.QLabel(self.layoutWidget4)
        self.officeEmailLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.officeEmailLabel.setObjectName(_fromUtf8("officeEmailLabel"))
        self.gridLayout_3.addWidget(self.officeEmailLabel, 0, 0, 1, 1)
        self.officeEmailLineEdit = QtGui.QLineEdit(self.layoutWidget4)
        self.officeEmailLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.officeEmailLineEdit.setObjectName(_fromUtf8("officeEmailLineEdit"))
        self.gridLayout_3.addWidget(self.officeEmailLineEdit, 0, 1, 1, 1)
        self.personalEmailLabel = QtGui.QLabel(self.layoutWidget4)
        self.personalEmailLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.personalEmailLabel.setObjectName(_fromUtf8("personalEmailLabel"))
        self.gridLayout_3.addWidget(self.personalEmailLabel, 1, 0, 1, 1)
        self.personalEmailLineEdit = QtGui.QLineEdit(self.layoutWidget4)
        self.personalEmailLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.personalEmailLineEdit.setObjectName(_fromUtf8("personalEmailLineEdit"))
        self.gridLayout_3.addWidget(self.personalEmailLineEdit, 1, 1, 1, 1)
        self.officeWebLabel = QtGui.QLabel(self.layoutWidget4)
        self.officeWebLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.officeWebLabel.setObjectName(_fromUtf8("officeWebLabel"))
        self.gridLayout_3.addWidget(self.officeWebLabel, 2, 0, 1, 1)
        self.officeWebLineEdit = QtGui.QLineEdit(self.layoutWidget4)
        self.officeWebLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.officeWebLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.officeWebLineEdit.setObjectName(_fromUtf8("officeWebLineEdit"))
        self.gridLayout_3.addWidget(self.officeWebLineEdit, 2, 1, 1, 1)
        self.personalWebLabel = QtGui.QLabel(self.layoutWidget4)
        self.personalWebLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.personalWebLabel.setObjectName(_fromUtf8("personalWebLabel"))
        self.gridLayout_3.addWidget(self.personalWebLabel, 3, 0, 1, 1)
        self.personalWebLineEdit = QtGui.QLineEdit(self.layoutWidget4)
        self.personalWebLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.personalWebLineEdit.setObjectName(_fromUtf8("personalWebLineEdit"))
        self.gridLayout_3.addWidget(self.personalWebLineEdit, 3, 1, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/contact-new-2.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactTabWidget.addTab(self.contactTab, icon2, _fromUtf8(""))
        self.addressTab = QtGui.QWidget()
        self.addressTab.setObjectName(_fromUtf8("addressTab"))
        self.frame = QtGui.QFrame(self.addressTab)
        self.frame.setGeometry(QtCore.QRect(19, 39, 581, 271))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.layoutWidget5 = QtGui.QWidget(self.addressTab)
        self.layoutWidget5.setGeometry(QtCore.QRect(40, 70, 541, 221))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.addressLlabel = QtGui.QLabel(self.layoutWidget5)
        self.addressLlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.addressLlabel.setObjectName(_fromUtf8("addressLlabel"))
        self.gridLayout.addWidget(self.addressLlabel, 0, 0, 1, 1)
        self.addressLineEdit = QtGui.QLineEdit(self.layoutWidget5)
        self.addressLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.addressLineEdit.setObjectName(_fromUtf8("addressLineEdit"))
        self.gridLayout.addWidget(self.addressLineEdit, 0, 1, 1, 1)
        self.suiteLabel = QtGui.QLabel(self.layoutWidget5)
        self.suiteLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.suiteLabel.setObjectName(_fromUtf8("suiteLabel"))
        self.gridLayout.addWidget(self.suiteLabel, 1, 0, 1, 1)
        self.suiteLineEdit = QtGui.QLineEdit(self.layoutWidget5)
        self.suiteLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.suiteLineEdit.setObjectName(_fromUtf8("suiteLineEdit"))
        self.gridLayout.addWidget(self.suiteLineEdit, 1, 1, 1, 1)
        self.cityLabel = QtGui.QLabel(self.layoutWidget5)
        self.cityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cityLabel.setObjectName(_fromUtf8("cityLabel"))
        self.gridLayout.addWidget(self.cityLabel, 2, 0, 1, 1)
        self.cityLineEdit = QtGui.QLineEdit(self.layoutWidget5)
        self.cityLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.cityLineEdit.setObjectName(_fromUtf8("cityLineEdit"))
        self.gridLayout.addWidget(self.cityLineEdit, 2, 1, 1, 1)
        self.stateLabel = QtGui.QLabel(self.layoutWidget5)
        self.stateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stateLabel.setObjectName(_fromUtf8("stateLabel"))
        self.gridLayout.addWidget(self.stateLabel, 3, 0, 1, 1)
        self.stateLineEdit = QtGui.QLineEdit(self.layoutWidget5)
        self.stateLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.stateLineEdit.setObjectName(_fromUtf8("stateLineEdit"))
        self.gridLayout.addWidget(self.stateLineEdit, 3, 1, 1, 1)
        self.postalLabel = QtGui.QLabel(self.layoutWidget5)
        self.postalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.postalLabel.setObjectName(_fromUtf8("postalLabel"))
        self.gridLayout.addWidget(self.postalLabel, 4, 0, 1, 1)
        self.postalLineEdit = QtGui.QLineEdit(self.layoutWidget5)
        self.postalLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.postalLineEdit.setObjectName(_fromUtf8("postalLineEdit"))
        self.gridLayout.addWidget(self.postalLineEdit, 4, 1, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/address-book-new-2.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactTabWidget.addTab(self.addressTab, icon3, _fromUtf8(""))
        self.mapTab = QtGui.QWidget()
        self.mapTab.setObjectName(_fromUtf8("mapTab"))
        self.mapTabFrame = QtGui.QFrame(self.mapTab)
        self.mapTabFrame.setGeometry(QtCore.QRect(9, 9, 591, 361))
        self.mapTabFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mapTabFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mapTabFrame.setObjectName(_fromUtf8("mapTabFrame"))
        self.refreshMapPushButton = QtGui.QPushButton(self.mapTab)
        self.refreshMapPushButton.setGeometry(QtCore.QRect(530, 380, 61, 27))
        self.refreshMapPushButton.setObjectName(_fromUtf8("refreshMapPushButton"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/Bevel-And-Emboss-Media-Map.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactTabWidget.addTab(self.mapTab, icon4, _fromUtf8(""))
        self.notesTab = QtGui.QWidget()
        self.notesTab.setObjectName(_fromUtf8("notesTab"))
        self.notesFrame = QtGui.QFrame(self.notesTab)
        self.notesFrame.setGeometry(QtCore.QRect(9, 9, 591, 371))
        self.notesFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.notesFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.notesFrame.setObjectName(_fromUtf8("notesFrame"))
        self.notesTableWidget = QtGui.QTableWidget(self.notesFrame)
        self.notesTableWidget.setGeometry(QtCore.QRect(10, 10, 571, 321))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesTableWidget.sizePolicy().hasHeightForWidth())
        self.notesTableWidget.setSizePolicy(sizePolicy)
        self.notesTableWidget.setMaximumSize(QtCore.QSize(16777215, 321))
        self.notesTableWidget.setAcceptDrops(True)
        self.notesTableWidget.setMidLineWidth(1)
        self.notesTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.notesTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.notesTableWidget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.notesTableWidget.setDragEnabled(True)
        self.notesTableWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.notesTableWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.notesTableWidget.setAlternatingRowColors(True)
        self.notesTableWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.notesTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.notesTableWidget.setWordWrap(True)
        self.notesTableWidget.setRowCount(2000)
        self.notesTableWidget.setColumnCount(2)
        self.notesTableWidget.setObjectName(_fromUtf8("notesTableWidget"))
        self.notesTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.notesTableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.notesTableWidget.horizontalHeader().setMinimumSectionSize(56)
        self.notesTableWidget.horizontalHeader().setStretchLastSection(True)
        self.notesTableWidget.verticalHeader().setVisible(False)
        self.notesTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.notesTableWidget.verticalHeader().setDefaultSectionSize(50)
        self.notesDetailPushButton = QtGui.QPushButton(self.notesFrame)
        self.notesDetailPushButton.setGeometry(QtCore.QRect(500, 340, 61, 27))
        self.notesDetailPushButton.setObjectName(_fromUtf8("notesDetailPushButton"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/document-sign.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactTabWidget.addTab(self.notesTab, icon5, _fromUtf8(""))
        self.fileTab = QtGui.QWidget()
        self.fileTab.setObjectName(_fromUtf8("fileTab"))
        self.fileFrame = QtGui.QFrame(self.fileTab)
        self.fileFrame.setGeometry(QtCore.QRect(9, 9, 591, 371))
        self.fileFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fileFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.fileFrame.setObjectName(_fromUtf8("fileFrame"))
        self.fileTableWidget = QtGui.QTableWidget(self.fileFrame)
        self.fileTableWidget.setGeometry(QtCore.QRect(10, 10, 571, 321))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileTableWidget.sizePolicy().hasHeightForWidth())
        self.fileTableWidget.setSizePolicy(sizePolicy)
        self.fileTableWidget.setMaximumSize(QtCore.QSize(16777215, 321))
        self.fileTableWidget.setAcceptDrops(True)
        self.fileTableWidget.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.fileTableWidget.setMidLineWidth(1)
        self.fileTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.fileTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.fileTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.fileTableWidget.setDragEnabled(True)
        self.fileTableWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.fileTableWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.fileTableWidget.setAlternatingRowColors(True)
        self.fileTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.fileTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.fileTableWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.fileTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.fileTableWidget.setWordWrap(True)
        self.fileTableWidget.setRowCount(2000)
        self.fileTableWidget.setColumnCount(3)
        self.fileTableWidget.setObjectName(_fromUtf8("fileTableWidget"))
        self.fileTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.fileTableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.fileTableWidget.horizontalHeader().setMinimumSectionSize(45)
        self.fileTableWidget.horizontalHeader().setStretchLastSection(True)
        self.fileTableWidget.verticalHeader().setVisible(False)
        self.fileTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.fileTableWidget.verticalHeader().setDefaultSectionSize(30)
        self.filePushButton = QtGui.QPushButton(self.fileFrame)
        self.filePushButton.setGeometry(QtCore.QRect(530, 340, 31, 27))
        self.filePushButton.setText(_fromUtf8(""))
        self.filePushButton.setIcon(icon1)
        self.filePushButton.setObjectName(_fromUtf8("filePushButton"))
        self.contactTabWidget.addTab(self.fileTab, icon1, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.activityTabWidget = QtGui.QTabWidget(self.tab)
        self.activityTabWidget.setGeometry(QtCore.QRect(12, 9, 591, 391))
        self.activityTabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.activityTabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.activityTabWidget.setDocumentMode(True)
        self.activityTabWidget.setMovable(True)
        self.activityTabWidget.setObjectName(_fromUtf8("activityTabWidget"))
        self.phoneCallsTab = QtGui.QWidget()
        self.phoneCallsTab.setObjectName(_fromUtf8("phoneCallsTab"))
        self.notesFrame_2 = QtGui.QFrame(self.phoneCallsTab)
        self.notesFrame_2.setGeometry(QtCore.QRect(-10, -10, 591, 371))
        self.notesFrame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.notesFrame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.notesFrame_2.setObjectName(_fromUtf8("notesFrame_2"))
        self.callsTableWidget = QtGui.QTableWidget(self.notesFrame_2)
        self.callsTableWidget.setGeometry(QtCore.QRect(20, 20, 561, 311))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.callsTableWidget.sizePolicy().hasHeightForWidth())
        self.callsTableWidget.setSizePolicy(sizePolicy)
        self.callsTableWidget.setMaximumSize(QtCore.QSize(16777215, 321))
        self.callsTableWidget.setAcceptDrops(True)
        self.callsTableWidget.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.callsTableWidget.setMidLineWidth(1)
        self.callsTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.callsTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.callsTableWidget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.callsTableWidget.setDragEnabled(True)
        self.callsTableWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.callsTableWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.callsTableWidget.setAlternatingRowColors(True)
        self.callsTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.callsTableWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.callsTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.callsTableWidget.setWordWrap(True)
        self.callsTableWidget.setRowCount(2000)
        self.callsTableWidget.setColumnCount(6)
        self.callsTableWidget.setObjectName(_fromUtf8("callsTableWidget"))
        self.callsTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.callsTableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.callsTableWidget.horizontalHeader().setMinimumSectionSize(56)
        self.callsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.callsTableWidget.verticalHeader().setVisible(False)
        self.callsTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.callsTableWidget.verticalHeader().setDefaultSectionSize(50)
        self.callsDetailPushButton = QtGui.QPushButton(self.notesFrame_2)
        self.callsDetailPushButton.setGeometry(QtCore.QRect(500, 340, 61, 27))
        self.callsDetailPushButton.setObjectName(_fromUtf8("callsDetailPushButton"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/call-start.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.activityTabWidget.addTab(self.phoneCallsTab, icon6, _fromUtf8(""))
        self.eMailsTab = QtGui.QWidget()
        self.eMailsTab.setObjectName(_fromUtf8("eMailsTab"))
        self.emailFrame = QtGui.QFrame(self.eMailsTab)
        self.emailFrame.setGeometry(QtCore.QRect(0, 10, 591, 311))
        self.emailFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.emailFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.emailFrame.setObjectName(_fromUtf8("emailFrame"))
        self.emailRefreshPushButton = QtGui.QPushButton(self.eMailsTab)
        self.emailRefreshPushButton.setGeometry(QtCore.QRect(500, 330, 61, 27))
        self.emailRefreshPushButton.setObjectName(_fromUtf8("emailRefreshPushButton"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/mail-generic-2.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.activityTabWidget.addTab(self.eMailsTab, icon7, _fromUtf8(""))
        self.appointmentTab = QtGui.QWidget()
        self.appointmentTab.setObjectName(_fromUtf8("appointmentTab"))
        self.apptFrame = QtGui.QFrame(self.appointmentTab)
        self.apptFrame.setGeometry(QtCore.QRect(9, 9, 571, 341))
        self.apptFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.apptFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.apptFrame.setObjectName(_fromUtf8("apptFrame"))
        self.apptTableWidget = QtGui.QTableWidget(self.apptFrame)
        self.apptTableWidget.setGeometry(QtCore.QRect(10, 10, 551, 291))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apptTableWidget.sizePolicy().hasHeightForWidth())
        self.apptTableWidget.setSizePolicy(sizePolicy)
        self.apptTableWidget.setMaximumSize(QtCore.QSize(16777215, 321))
        self.apptTableWidget.setAcceptDrops(True)
        self.apptTableWidget.setStyleSheet(_fromUtf8("background-color: rgb(211, 213, 244);"))
        self.apptTableWidget.setMidLineWidth(1)
        self.apptTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.apptTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.apptTableWidget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.apptTableWidget.setDragEnabled(True)
        self.apptTableWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.apptTableWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.apptTableWidget.setAlternatingRowColors(True)
        self.apptTableWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.apptTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.apptTableWidget.setWordWrap(True)
        self.apptTableWidget.setRowCount(2000)
        self.apptTableWidget.setColumnCount(6)
        self.apptTableWidget.setObjectName(_fromUtf8("apptTableWidget"))
        self.apptTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.apptTableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.apptTableWidget.horizontalHeader().setMinimumSectionSize(56)
        self.apptTableWidget.horizontalHeader().setStretchLastSection(True)
        self.apptTableWidget.verticalHeader().setVisible(False)
        self.apptTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.apptTableWidget.verticalHeader().setDefaultSectionSize(50)
        self.apptDetailPushButton = QtGui.QPushButton(self.apptFrame)
        self.apptDetailPushButton.setGeometry(QtCore.QRect(460, 310, 61, 27))
        self.apptDetailPushButton.setObjectName(_fromUtf8("apptDetailPushButton"))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/appointment-new-2.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.activityTabWidget.addTab(self.appointmentTab, icon8, _fromUtf8(""))
        self.calendarTab = QtGui.QWidget()
        self.calendarTab.setObjectName(_fromUtf8("calendarTab"))
        self.calendarWidget = QtGui.QCalendarWidget(self.calendarTab)
        self.calendarWidget.setGeometry(QtCore.QRect(-5, 1, 581, 351))
        self.calendarWidget.setAutoFillBackground(True)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/view-calendar-month.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.activityTabWidget.addTab(self.calendarTab, icon9, _fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/edit-group.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactTabWidget.addTab(self.tab, icon10, _fromUtf8(""))
        self.line = QtGui.QFrame(contactsSearchDialog)
        self.line.setGeometry(QtCore.QRect(10, 150, 611, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(contactsSearchDialog)
        self.label.setGeometry(QtCore.QRect(10, 620, 161, 21))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/bristo_logo.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.credLabel.setBuddy(self.credLineEdit)
        self.mrmrsLabel.setBuddy(self.mrmrsLineEdit)
        self.firstnameLabel.setBuddy(self.firstNameLineEdit)
        self.middleNameLabel.setBuddy(self.middleNameLineEdit)
        self.lastNameLabel.setBuddy(self.lastNameLineEdit)
        self.companyLabel.setBuddy(self.companyLineEdit)
        self.cellPhoneLabel.setBuddy(self.cellPhoneLineEdit)
        self.homePhoneLabel.setBuddy(self.homePhoneLineEdit)
        self.officePhoneLabel.setBuddy(self.officePhoneLineEdit)
        self.officeFaxLabel.setBuddy(self.officeFaxLineEdit)
        self.officeEmailLabel.setBuddy(self.officeEmailLineEdit)
        self.personalEmailLabel.setBuddy(self.personalEmailLineEdit)
        self.officeWebLabel.setBuddy(self.officeWebLineEdit)
        self.personalWebLabel.setBuddy(self.personalWebLineEdit)
        self.addressLlabel.setBuddy(self.addressLineEdit)
        self.suiteLabel.setBuddy(self.suiteLineEdit)
        self.cityLabel.setBuddy(self.cityLineEdit)
        self.stateLabel.setBuddy(self.stateLineEdit)
        self.postalLabel.setBuddy(self.postalLineEdit)

        self.retranslateUi(contactsSearchDialog)
        self.contactTabWidget.setCurrentIndex(0)
        self.activityTabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(contactsSearchDialog)
        contactsSearchDialog.setTabOrder(self.companyLineEdit, self.mrmrsLineEdit)
        contactsSearchDialog.setTabOrder(self.mrmrsLineEdit, self.firstNameLineEdit)
        contactsSearchDialog.setTabOrder(self.firstNameLineEdit, self.middleNameLineEdit)
        contactsSearchDialog.setTabOrder(self.middleNameLineEdit, self.lastNameLineEdit)
        contactsSearchDialog.setTabOrder(self.lastNameLineEdit, self.credLineEdit)
        contactsSearchDialog.setTabOrder(self.credLineEdit, self.cellPhoneLineEdit)
        contactsSearchDialog.setTabOrder(self.cellPhoneLineEdit, self.homePhoneLineEdit)
        contactsSearchDialog.setTabOrder(self.homePhoneLineEdit, self.officePhoneLineEdit)
        contactsSearchDialog.setTabOrder(self.officePhoneLineEdit, self.officeFaxLineEdit)
        contactsSearchDialog.setTabOrder(self.officeFaxLineEdit, self.officeEmailLineEdit)
        contactsSearchDialog.setTabOrder(self.officeEmailLineEdit, self.personalEmailLineEdit)
        contactsSearchDialog.setTabOrder(self.personalEmailLineEdit, self.officeWebLineEdit)
        contactsSearchDialog.setTabOrder(self.officeWebLineEdit, self.personalWebLineEdit)
        contactsSearchDialog.setTabOrder(self.personalWebLineEdit, self.picPushButton)
        contactsSearchDialog.setTabOrder(self.picPushButton, self.addressLineEdit)
        contactsSearchDialog.setTabOrder(self.addressLineEdit, self.suiteLineEdit)
        contactsSearchDialog.setTabOrder(self.suiteLineEdit, self.cityLineEdit)
        contactsSearchDialog.setTabOrder(self.cityLineEdit, self.stateLineEdit)
        contactsSearchDialog.setTabOrder(self.stateLineEdit, self.postalLineEdit)
        contactsSearchDialog.setTabOrder(self.postalLineEdit, self.contactTabWidget)
        contactsSearchDialog.setTabOrder(self.contactTabWidget, self.notesTableWidget)
        contactsSearchDialog.setTabOrder(self.notesTableWidget, self.notesDetailPushButton)
        contactsSearchDialog.setTabOrder(self.notesDetailPushButton, self.fileTableWidget)
        contactsSearchDialog.setTabOrder(self.fileTableWidget, self.filePushButton)

    def retranslateUi(self, contactsSearchDialog):
        contactsSearchDialog.setWindowTitle(_translate("contactsSearchDialog", "Contacts Dialog", None))
        self.credLabel.setText(_translate("contactsSearchDialog", "Title:", None))
        self.mrmrsLabel.setText(_translate("contactsSearchDialog", "Mr/Mrs:", None))
        self.firstnameLabel.setText(_translate("contactsSearchDialog", "First :", None))
        self.firstNameLineEdit.setPlaceholderText(_translate("contactsSearchDialog", "Search: First Name", None))
        self.middleNameLabel.setText(_translate("contactsSearchDialog", "M:", None))
        self.lastNameLabel.setText(_translate("contactsSearchDialog", "Last:", None))
        self.lastNameLineEdit.setPlaceholderText(_translate("contactsSearchDialog", "Search: Last Name", None))
        self.companyLabel.setText(_translate("contactsSearchDialog", "Company/Organization:", None))
        self.companyLineEdit.setPlaceholderText(_translate("contactsSearchDialog", "Search: Company Name", None))
        self.picPushButton.setToolTip(_translate("contactsSearchDialog", "Add Picture", None))
        self.cellPhoneLabel.setText(_translate("contactsSearchDialog", "Cell Phone:", None))
        self.homePhoneLabel.setText(_translate("contactsSearchDialog", "Home Phone:", None))
        self.officePhoneLabel.setText(_translate("contactsSearchDialog", "Office Phone:", None))
        self.officeFaxLabel.setText(_translate("contactsSearchDialog", "Office Fax:", None))
        self.officeEmailLabel.setText(_translate("contactsSearchDialog", "Office Email:", None))
        self.personalEmailLabel.setText(_translate("contactsSearchDialog", "Personal Email:", None))
        self.officeWebLabel.setText(_translate("contactsSearchDialog", "Office Web:", None))
        self.personalWebLabel.setText(_translate("contactsSearchDialog", "Personal Web:", None))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.contactTab), _translate("contactsSearchDialog", "Contact", None))
        self.addressLlabel.setText(_translate("contactsSearchDialog", "Address:", None))
        self.suiteLabel.setText(_translate("contactsSearchDialog", "Suite/ Floor:", None))
        self.cityLabel.setText(_translate("contactsSearchDialog", "City:", None))
        self.stateLabel.setText(_translate("contactsSearchDialog", "State/Province:", None))
        self.postalLabel.setText(_translate("contactsSearchDialog", "Zip:", None))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.addressTab), _translate("contactsSearchDialog", "Address", None))
        self.refreshMapPushButton.setText(_translate("contactsSearchDialog", "Refresh", None))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.mapTab), _translate("contactsSearchDialog", "Map", None))
        self.notesTableWidget.setSortingEnabled(True)
        self.notesDetailPushButton.setText(_translate("contactsSearchDialog", "Resize", None))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.notesTab), _translate("contactsSearchDialog", "Notes", None))
        self.fileTableWidget.setSortingEnabled(True)
        self.filePushButton.setToolTip(_translate("contactsSearchDialog", "Add New File", None))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.fileTab), _translate("contactsSearchDialog", "Files", None))
        self.callsTableWidget.setSortingEnabled(True)
        self.callsDetailPushButton.setText(_translate("contactsSearchDialog", "Resize", None))
        self.activityTabWidget.setTabText(self.activityTabWidget.indexOf(self.phoneCallsTab), _translate("contactsSearchDialog", "Phone Calls", None))
        self.emailRefreshPushButton.setText(_translate("contactsSearchDialog", "Refresh", None))
        self.activityTabWidget.setTabText(self.activityTabWidget.indexOf(self.eMailsTab), _translate("contactsSearchDialog", "eMails", None))
        self.apptTableWidget.setSortingEnabled(True)
        self.apptDetailPushButton.setText(_translate("contactsSearchDialog", "Resize", None))
        self.activityTabWidget.setTabText(self.activityTabWidget.indexOf(self.appointmentTab), _translate("contactsSearchDialog", "Appointments/Meetings", None))
        self.activityTabWidget.setTabText(self.activityTabWidget.indexOf(self.calendarTab), _translate("contactsSearchDialog", "Calendar", None))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.tab), _translate("contactsSearchDialog", "Activity", None))

import resources_rc
