# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchgroup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_searchGroupDialog(object):
    def setupUi(self, searchGroupDialog):
        searchGroupDialog.setObjectName(_fromUtf8("searchGroupDialog"))
        searchGroupDialog.resize(632, 655)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/edit-user.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        searchGroupDialog.setWindowIcon(icon)
        searchGroupDialog.setWindowOpacity(1.0)
        searchGroupDialog.setStyleSheet(_fromUtf8(""))
        self.credentialsFrame = QtGui.QFrame(searchGroupDialog)
        self.credentialsFrame.setGeometry(QtCore.QRect(10, 10, 611, 181))
        self.credentialsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.credentialsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.credentialsFrame.setObjectName(_fromUtf8("credentialsFrame"))
        self.layoutWidget = QtGui.QWidget(self.credentialsFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 14, 591, 161))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupLabel = QtGui.QLabel(self.layoutWidget)
        self.groupLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupLabel.setObjectName(_fromUtf8("groupLabel"))
        self.gridLayout.addWidget(self.groupLabel, 0, 0, 1, 1)
        self.searchGroupLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.searchGroupLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.searchGroupLineEdit.setObjectName(_fromUtf8("searchGroupLineEdit"))
        self.gridLayout.addWidget(self.searchGroupLineEdit, 0, 1, 1, 1)
        self.passwordLabel = QtGui.QLabel(self.layoutWidget)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passwordLabel.setObjectName(_fromUtf8("passwordLabel"))
        self.gridLayout.addWidget(self.passwordLabel, 1, 0, 1, 1)
        self.passwordLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.passwordLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(153, 204, 255)"))
        self.passwordLineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.passwordLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordLineEdit.setObjectName(_fromUtf8("passwordLineEdit"))
        self.gridLayout.addWidget(self.passwordLineEdit, 1, 1, 1, 1)
        self.confirmPasswordLabel = QtGui.QLabel(self.layoutWidget)
        self.confirmPasswordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.confirmPasswordLabel.setObjectName(_fromUtf8("confirmPasswordLabel"))
        self.gridLayout.addWidget(self.confirmPasswordLabel, 2, 0, 1, 1)
        self.confirmPasswordLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.confirmPasswordLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(153, 204, 255)"))
        self.confirmPasswordLineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.confirmPasswordLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.confirmPasswordLineEdit.setObjectName(_fromUtf8("confirmPasswordLineEdit"))
        self.gridLayout.addWidget(self.confirmPasswordLineEdit, 2, 1, 1, 1)
        self.newGroupTabWidget = QtGui.QTabWidget(searchGroupDialog)
        self.newGroupTabWidget.setGeometry(QtCore.QRect(10, 220, 611, 401))
        self.newGroupTabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.newGroupTabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.newGroupTabWidget.setTabsClosable(False)
        self.newGroupTabWidget.setMovable(True)
        self.newGroupTabWidget.setObjectName(_fromUtf8("newGroupTabWidget"))
        self.groupDescriptionTab = QtGui.QWidget()
        self.groupDescriptionTab.setObjectName(_fromUtf8("groupDescriptionTab"))
        self.descriptionFrame = QtGui.QFrame(self.groupDescriptionTab)
        self.descriptionFrame.setGeometry(QtCore.QRect(10, 10, 581, 271))
        self.descriptionFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.descriptionFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.descriptionFrame.setLineWidth(2)
        self.descriptionFrame.setObjectName(_fromUtf8("descriptionFrame"))
        self.descTextEdit = QtGui.QTextEdit(self.descriptionFrame)
        self.descTextEdit.setGeometry(QtCore.QRect(13, 17, 551, 241))
        self.descTextEdit.setStyleSheet(_fromUtf8("background-color: rgb(245,245,245);"))
        self.descTextEdit.setObjectName(_fromUtf8("descTextEdit"))
        self.newGroupLabel = QtGui.QLabel(self.groupDescriptionTab)
        self.newGroupLabel.setGeometry(QtCore.QRect(380, 320, 211, 31))
        self.newGroupLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.newGroupLabel.setText(_fromUtf8(""))
        self.newGroupLabel.setPixmap(QtGui.QPixmap(_fromUtf8("bristo_logo.png")))
        self.newGroupLabel.setScaledContents(True)
        self.newGroupLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newGroupLabel.setObjectName(_fromUtf8("newGroupLabel"))
        self.picPushButton = QtGui.QPushButton(self.groupDescriptionTab)
        self.picPushButton.setGeometry(QtCore.QRect(330, 330, 38, 27))
        self.picPushButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/document-open-2.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.picPushButton.setIcon(icon1)
        self.picPushButton.setObjectName(_fromUtf8("picPushButton"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/edit-group.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newGroupTabWidget.addTab(self.groupDescriptionTab, icon2, _fromUtf8(""))
        self.groupAddressTab = QtGui.QWidget()
        self.groupAddressTab.setObjectName(_fromUtf8("groupAddressTab"))
        self.groupAddressFrame_2 = QtGui.QFrame(self.groupAddressTab)
        self.groupAddressFrame_2.setGeometry(QtCore.QRect(10, 50, 581, 271))
        self.groupAddressFrame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.groupAddressFrame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.groupAddressFrame_2.setLineWidth(2)
        self.groupAddressFrame_2.setObjectName(_fromUtf8("groupAddressFrame_2"))
        self.layoutWidget_4 = QtGui.QWidget(self.groupAddressFrame_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 20, 541, 221))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupAddressLabel_2 = QtGui.QLabel(self.layoutWidget_4)
        self.groupAddressLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupAddressLabel_2.setObjectName(_fromUtf8("groupAddressLabel_2"))
        self.gridLayout_5.addWidget(self.groupAddressLabel_2, 0, 0, 1, 1)
        self.groupAddressLineEdit = QtGui.QLineEdit(self.layoutWidget_4)
        self.groupAddressLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.groupAddressLineEdit.setObjectName(_fromUtf8("groupAddressLineEdit"))
        self.gridLayout_5.addWidget(self.groupAddressLineEdit, 0, 1, 1, 1)
        self.groupSuiteLabel_2 = QtGui.QLabel(self.layoutWidget_4)
        self.groupSuiteLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupSuiteLabel_2.setObjectName(_fromUtf8("groupSuiteLabel_2"))
        self.gridLayout_5.addWidget(self.groupSuiteLabel_2, 1, 0, 1, 1)
        self.groupSuiteLineEdit = QtGui.QLineEdit(self.layoutWidget_4)
        self.groupSuiteLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.groupSuiteLineEdit.setObjectName(_fromUtf8("groupSuiteLineEdit"))
        self.gridLayout_5.addWidget(self.groupSuiteLineEdit, 1, 1, 1, 1)
        self.groupCityLabel_2 = QtGui.QLabel(self.layoutWidget_4)
        self.groupCityLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupCityLabel_2.setObjectName(_fromUtf8("groupCityLabel_2"))
        self.gridLayout_5.addWidget(self.groupCityLabel_2, 2, 0, 1, 1)
        self.groupCityLineEdit = QtGui.QLineEdit(self.layoutWidget_4)
        self.groupCityLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.groupCityLineEdit.setObjectName(_fromUtf8("groupCityLineEdit"))
        self.gridLayout_5.addWidget(self.groupCityLineEdit, 2, 1, 1, 1)
        self.groupStateLabel_2 = QtGui.QLabel(self.layoutWidget_4)
        self.groupStateLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupStateLabel_2.setObjectName(_fromUtf8("groupStateLabel_2"))
        self.gridLayout_5.addWidget(self.groupStateLabel_2, 3, 0, 1, 1)
        self.groupStateLineEdit = QtGui.QLineEdit(self.layoutWidget_4)
        self.groupStateLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.groupStateLineEdit.setObjectName(_fromUtf8("groupStateLineEdit"))
        self.gridLayout_5.addWidget(self.groupStateLineEdit, 3, 1, 1, 1)
        self.groupPostalLabel_2 = QtGui.QLabel(self.layoutWidget_4)
        self.groupPostalLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupPostalLabel_2.setObjectName(_fromUtf8("groupPostalLabel_2"))
        self.gridLayout_5.addWidget(self.groupPostalLabel_2, 4, 0, 1, 1)
        self.groupPostalLineEdit = QtGui.QLineEdit(self.layoutWidget_4)
        self.groupPostalLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(215, 255, 208);"))
        self.groupPostalLineEdit.setObjectName(_fromUtf8("groupPostalLineEdit"))
        self.gridLayout_5.addWidget(self.groupPostalLineEdit, 4, 1, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/address-book-new-2.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newGroupTabWidget.addTab(self.groupAddressTab, icon3, _fromUtf8(""))
        self.groupContactTab = QtGui.QWidget()
        self.groupContactTab.setObjectName(_fromUtf8("groupContactTab"))
        self.groupContactFrame_2 = QtGui.QFrame(self.groupContactTab)
        self.groupContactFrame_2.setGeometry(QtCore.QRect(10, 50, 591, 271))
        self.groupContactFrame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.groupContactFrame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.groupContactFrame_2.setObjectName(_fromUtf8("groupContactFrame_2"))
        self.layoutWidget_5 = QtGui.QWidget(self.groupContactFrame_2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 20, 551, 231))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupOfficeWebLabel_2 = QtGui.QLabel(self.layoutWidget_5)
        self.groupOfficeWebLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupOfficeWebLabel_2.setObjectName(_fromUtf8("groupOfficeWebLabel_2"))
        self.gridLayout_6.addWidget(self.groupOfficeWebLabel_2, 2, 0, 1, 1)
        self.groupOfficeFaxLineEdit = QtGui.QLineEdit(self.layoutWidget_5)
        self.groupOfficeFaxLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.groupOfficeFaxLineEdit.setObjectName(_fromUtf8("groupOfficeFaxLineEdit"))
        self.gridLayout_6.addWidget(self.groupOfficeFaxLineEdit, 1, 1, 1, 1)
        self.groupOfficeWebLineEdit = QtGui.QLineEdit(self.layoutWidget_5)
        self.groupOfficeWebLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.groupOfficeWebLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupOfficeWebLineEdit.setObjectName(_fromUtf8("groupOfficeWebLineEdit"))
        self.gridLayout_6.addWidget(self.groupOfficeWebLineEdit, 2, 1, 1, 1)
        self.groupOfficeFaxLabel_2 = QtGui.QLabel(self.layoutWidget_5)
        self.groupOfficeFaxLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupOfficeFaxLabel_2.setObjectName(_fromUtf8("groupOfficeFaxLabel_2"))
        self.gridLayout_6.addWidget(self.groupOfficeFaxLabel_2, 1, 0, 1, 1)
        self.groupOfficePhoneLineEdit = QtGui.QLineEdit(self.layoutWidget_5)
        self.groupOfficePhoneLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.groupOfficePhoneLineEdit.setObjectName(_fromUtf8("groupOfficePhoneLineEdit"))
        self.gridLayout_6.addWidget(self.groupOfficePhoneLineEdit, 0, 1, 1, 1)
        self.groupOtherWebLineEdit = QtGui.QLineEdit(self.layoutWidget_5)
        self.groupOtherWebLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 250, 217)"))
        self.groupOtherWebLineEdit.setObjectName(_fromUtf8("groupOtherWebLineEdit"))
        self.gridLayout_6.addWidget(self.groupOtherWebLineEdit, 3, 1, 1, 1)
        self.groupOtherWebLabel_2 = QtGui.QLabel(self.layoutWidget_5)
        self.groupOtherWebLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupOtherWebLabel_2.setObjectName(_fromUtf8("groupOtherWebLabel_2"))
        self.gridLayout_6.addWidget(self.groupOtherWebLabel_2, 3, 0, 1, 1)
        self.groupOfficePhoneLabel_2 = QtGui.QLabel(self.layoutWidget_5)
        self.groupOfficePhoneLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupOfficePhoneLabel_2.setObjectName(_fromUtf8("groupOfficePhoneLabel_2"))
        self.gridLayout_6.addWidget(self.groupOfficePhoneLabel_2, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/contact-new-2.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newGroupTabWidget.addTab(self.groupContactTab, icon4, _fromUtf8(""))
        self.line = QtGui.QFrame(searchGroupDialog)
        self.line.setGeometry(QtCore.QRect(10, 200, 611, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.groupLabel.setBuddy(self.searchGroupLineEdit)
        self.passwordLabel.setBuddy(self.passwordLineEdit)
        self.confirmPasswordLabel.setBuddy(self.confirmPasswordLineEdit)
        self.groupAddressLabel_2.setBuddy(self.groupAddressLineEdit)
        self.groupSuiteLabel_2.setBuddy(self.groupSuiteLineEdit)
        self.groupCityLabel_2.setBuddy(self.groupCityLineEdit)
        self.groupStateLabel_2.setBuddy(self.groupStateLineEdit)
        self.groupPostalLabel_2.setBuddy(self.groupPostalLineEdit)
        self.groupOfficeWebLabel_2.setBuddy(self.groupOfficeWebLineEdit)
        self.groupOfficeFaxLabel_2.setBuddy(self.groupOfficeFaxLineEdit)
        self.groupOtherWebLabel_2.setBuddy(self.groupOtherWebLineEdit)
        self.groupOfficePhoneLabel_2.setBuddy(self.groupOfficePhoneLineEdit)

        self.retranslateUi(searchGroupDialog)
        self.newGroupTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(searchGroupDialog)

    def retranslateUi(self, searchGroupDialog):
        searchGroupDialog.setWindowTitle(_translate("searchGroupDialog", "Search Group Dialog", None))
        self.groupLabel.setText(_translate("searchGroupDialog", "Group:", None))
        self.searchGroupLineEdit.setPlaceholderText(_translate("searchGroupDialog", "Search: Groups  and Group Name should not include spaces.", None))
        self.passwordLabel.setText(_translate("searchGroupDialog", "Password:", None))
        self.passwordLineEdit.setPlaceholderText(_translate("searchGroupDialog", "Password m/b 9 char, upper, lower, number and one special character.", None))
        self.confirmPasswordLabel.setText(_translate("searchGroupDialog", "Confirm:", None))
        self.confirmPasswordLineEdit.setPlaceholderText(_translate("searchGroupDialog", "Please re-enter the password.", None))
        self.picPushButton.setToolTip(_translate("searchGroupDialog", "Add Picture", None))
        self.newGroupTabWidget.setTabText(self.newGroupTabWidget.indexOf(self.groupDescriptionTab), _translate("searchGroupDialog", "Group Description", None))
        self.groupAddressLabel_2.setText(_translate("searchGroupDialog", "Address:", None))
        self.groupSuiteLabel_2.setText(_translate("searchGroupDialog", "Suite/ Floor:", None))
        self.groupCityLabel_2.setText(_translate("searchGroupDialog", "City:", None))
        self.groupStateLabel_2.setText(_translate("searchGroupDialog", "State/Province:", None))
        self.groupPostalLabel_2.setText(_translate("searchGroupDialog", "Zip:", None))
        self.newGroupTabWidget.setTabText(self.newGroupTabWidget.indexOf(self.groupAddressTab), _translate("searchGroupDialog", "Address", None))
        self.groupOfficeWebLabel_2.setText(_translate("searchGroupDialog", "Office Web:", None))
        self.groupOfficeFaxLabel_2.setText(_translate("searchGroupDialog", "Office Fax:", None))
        self.groupOtherWebLabel_2.setText(_translate("searchGroupDialog", "Other Web:", None))
        self.groupOfficePhoneLabel_2.setText(_translate("searchGroupDialog", "Office Phone:", None))
        self.newGroupTabWidget.setTabText(self.newGroupTabWidget.indexOf(self.groupContactTab), _translate("searchGroupDialog", "Contact", None))

import resources_rc
